name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java files
        run: |
          mkdir -p bin
          javac -d bin $(find middleware aplicacao -name "*.java")

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: edsonrs18
          projectKey: EdsonRS18_ProjetoSD
          projectName: teste
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
